"""create initial tables

Revision ID: 69b16d4208ea
Revises:
Create Date: 2026-08-17 16:12:18.857893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b16d4208ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooling_spots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('PUBLIC', 'COMPANY', name='cooling_spot_type', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('operating_days', sa.JSON(), nullable=True),
    sa.Column('facilities', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_cooling_spots_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_cooling_spots_longitude_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cooling_spots'))
    )
    op.create_table('visit_targets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_visit_targets_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_visit_targets_longitude_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit_targets'))
    )
    op.create_table('work_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('READY', 'IN_PROGRESS', 'COMPLETED', name='work_session_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_exposure_minutes', sa.Integer(), nullable=False),
    sa.Column('max_continuous_exposure_minutes', sa.Integer(), nullable=False),
    sa.Column('total_rest_minutes', sa.Integer(), nullable=False),
    sa.Column('rest_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_continuous_exposure_minutes >= 0', name=op.f('ck_work_sessions_max_continuous_exposure_minutes_nonnegative')),
    sa.CheckConstraint('rest_count >= 0', name=op.f('ck_work_sessions_rest_count_nonnegative')),
    sa.CheckConstraint('total_exposure_minutes >= 0', name=op.f('ck_work_sessions_total_exposure_minutes_nonnegative')),
    sa.CheckConstraint('total_rest_minutes >= 0', name=op.f('ck_work_sessions_total_rest_minutes_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_sessions'))
    )
    op.create_index(op.f('ix_work_sessions_work_date'), 'work_sessions', ['work_date'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('work_session_id', sa.BigInteger(), nullable=False),
    sa.Column('visit_target_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('visit_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='schedule_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('planned_visit_minutes', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('planned_visit_minutes IS NULL OR planned_visit_minutes >= 0', name=op.f('ck_schedules_planned_visit_minutes_nonnegative')),
    sa.CheckConstraint('visit_order > 0', name=op.f('ck_schedules_visit_order_positive')),
    sa.ForeignKeyConstraint(['visit_target_id'], ['visit_targets.id'], name=op.f('fk_schedules_visit_target_id_visit_targets')),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_schedules_work_session_id_work_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules')),
    sa.UniqueConstraint('work_session_id', 'visit_order', name='uq_schedule_visit_order')
    )
    op.create_index(op.f('ix_schedules_visit_target_id'), 'schedules', ['visit_target_id'], unique=False)
    op.create_index(op.f('ix_schedules_work_session_id'), 'schedules', ['work_session_id'], unique=False)
    op.create_table('route_segments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('origin_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('origin_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('destination_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('destination_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('destination_latitude BETWEEN -90 AND 90', name=op.f('ck_route_segments_destination_latitude_range')),
    sa.CheckConstraint('destination_longitude BETWEEN -180 AND 180', name=op.f('ck_route_segments_destination_longitude_range')),
    sa.CheckConstraint('origin_latitude BETWEEN -90 AND 90', name=op.f('ck_route_segments_origin_latitude_range')),
    sa.CheckConstraint('origin_longitude BETWEEN -180 AND 180', name=op.f('ck_route_segments_origin_longitude_range')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_route_segments_schedule_id_schedules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_segments'))
    )
    op.create_index(op.f('ix_route_segments_schedule_id'), 'route_segments', ['schedule_id'], unique=False)
    op.create_table('route_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('route_segment_id', sa.BigInteger(), nullable=False),
    sa.Column('cooling_spot_id', sa.BigInteger(), nullable=True),
    sa.Column('route_type', sa.Enum('NORMAL', 'SAFE', name='route_type', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('total_distance_meters', sa.Integer(), nullable=False),
    sa.Column('walking_minutes', sa.Integer(), nullable=False),
    sa.Column('total_travel_minutes', sa.Integer(), nullable=False),
    sa.Column('estimated_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('detour_distance_meters', sa.Integer(), nullable=True),
    sa.Column('additional_minutes', sa.Integer(), nullable=True),
    sa.Column('detour_ratio', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('minutes_to_cooling_spot', sa.Integer(), nullable=True),
    sa.Column('planned_rest_minutes', sa.Integer(), nullable=True),
    sa.Column('minutes_from_cooling_spot', sa.Integer(), nullable=True),
    sa.Column('cooling_spot_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('path', sa.JSON(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(route_type = 'NORMAL' AND cooling_spot_id IS NULL AND planned_rest_minutes IS NULL AND minutes_to_cooling_spot IS NULL AND minutes_from_cooling_spot IS NULL AND cooling_spot_arrival_time IS NULL) OR (route_type = 'SAFE' AND cooling_spot_id IS NOT NULL AND planned_rest_minutes IS NOT NULL AND minutes_to_cooling_spot IS NOT NULL AND minutes_from_cooling_spot IS NOT NULL AND cooling_spot_arrival_time IS NOT NULL)", name=op.f('ck_route_options_route_type_required_fields')),
    sa.CheckConstraint("route_type != 'NORMAL' OR total_travel_minutes = walking_minutes", name=op.f('ck_route_options_normal_travel_time')),
    sa.CheckConstraint("route_type != 'SAFE' OR total_travel_minutes = walking_minutes + planned_rest_minutes", name=op.f('ck_route_options_safe_travel_time')),
    sa.CheckConstraint("route_type != 'SAFE' OR walking_minutes = minutes_to_cooling_spot + minutes_from_cooling_spot", name=op.f('ck_route_options_safe_walking_time')),
    sa.CheckConstraint('additional_minutes IS NULL OR additional_minutes >= 0', name=op.f('ck_route_options_additional_minutes_nonnegative')),
    sa.CheckConstraint('detour_distance_meters IS NULL OR detour_distance_meters >= 0', name=op.f('ck_route_options_detour_distance_nonnegative')),
    sa.CheckConstraint('detour_ratio IS NULL OR detour_ratio >= 0', name=op.f('ck_route_options_detour_ratio_nonnegative')),
    sa.CheckConstraint('minutes_from_cooling_spot IS NULL OR minutes_from_cooling_spot >= 0', name=op.f('ck_route_options_minutes_from_cooling_spot_nonnegative')),
    sa.CheckConstraint('minutes_to_cooling_spot IS NULL OR minutes_to_cooling_spot >= 0', name=op.f('ck_route_options_minutes_to_cooling_spot_nonnegative')),
    sa.CheckConstraint('planned_rest_minutes IS NULL OR planned_rest_minutes >= 0', name=op.f('ck_route_options_planned_rest_minutes_nonnegative')),
    sa.CheckConstraint('selected IN (0, 1)', name=op.f('ck_route_options_selected_boolean')),
    sa.CheckConstraint('total_distance_meters >= 0', name=op.f('ck_route_options_distance_nonnegative')),
    sa.CheckConstraint('total_travel_minutes >= 0', name=op.f('ck_route_options_total_travel_minutes_nonnegative')),
    sa.CheckConstraint('walking_minutes >= 0', name=op.f('ck_route_options_walking_minutes_nonnegative')),
    sa.ForeignKeyConstraint(['cooling_spot_id'], ['cooling_spots.id'], name=op.f('fk_route_options_cooling_spot_id_cooling_spots')),
    sa.ForeignKeyConstraint(['route_segment_id'], ['route_segments.id'], name=op.f('fk_route_options_route_segment_id_route_segments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_options'))
    )
    op.create_index(op.f('ix_route_options_cooling_spot_id'), 'route_options', ['cooling_spot_id'], unique=False)
    op.create_index(op.f('ix_route_options_route_segment_id'), 'route_options', ['route_segment_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('work_session_id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=True),
    sa.Column('route_segment_id', sa.BigInteger(), nullable=True),
    sa.Column('route_option_id', sa.BigInteger(), nullable=True),
    sa.Column('cooling_spot_id', sa.BigInteger(), nullable=True),
    sa.Column('activity_type', sa.Enum('WORK_STARTED', 'NORMAL_ROUTE_SELECTED', 'SAFE_ROUTE_SELECTED', 'REST_COMPLETED', 'REST_SKIPPED', 'VISIT_COMPLETED', 'WORK_COMPLETED', name='activity_type', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('exposure_minutes', sa.Integer(), nullable=True),
    sa.Column('rest_minutes', sa.Integer(), nullable=True),
    sa.Column('rest_complied', sa.Boolean(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(activity_type = 'REST_COMPLETED' AND rest_complied = 1) OR (activity_type = 'REST_SKIPPED' AND rest_complied = 0) OR (activity_type NOT IN ('REST_COMPLETED', 'REST_SKIPPED') AND rest_complied IS NULL)", name=op.f('ck_activity_logs_rest_compliance_matches_activity')),
    sa.CheckConstraint('exposure_minutes IS NULL OR exposure_minutes >= 0', name=op.f('ck_activity_logs_exposure_minutes_nonnegative')),
    sa.CheckConstraint('rest_minutes IS NULL OR rest_minutes >= 0', name=op.f('ck_activity_logs_rest_minutes_nonnegative')),
    sa.ForeignKeyConstraint(['cooling_spot_id'], ['cooling_spots.id'], name=op.f('fk_activity_logs_cooling_spot_id_cooling_spots')),
    sa.ForeignKeyConstraint(['route_option_id'], ['route_options.id'], name=op.f('fk_activity_logs_route_option_id_route_options')),
    sa.ForeignKeyConstraint(['route_segment_id'], ['route_segments.id'], name=op.f('fk_activity_logs_route_segment_id_route_segments')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_activity_logs_schedule_id_schedules')),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], name=op.f('fk_activity_logs_work_session_id_work_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index(op.f('ix_activity_logs_cooling_spot_id'), 'activity_logs', ['cooling_spot_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_route_option_id'), 'activity_logs', ['route_option_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_route_segment_id'), 'activity_logs', ['route_segment_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_schedule_id'), 'activity_logs', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_work_session_id'), 'activity_logs', ['work_session_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('route_option_id', sa.BigInteger(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('apparent_temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('wbgt_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('walking_minutes', sa.Integer(), nullable=False),
    sa.Column('current_continuous_exposure_minutes', sa.Integer(), nullable=False),
    sa.Column('expected_continuous_exposure_minutes', sa.Integer(), nullable=False),
    sa.Column('shelter_accessibility', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.Enum('SAFE', 'CAUTION', 'REST_REQUIRED', name='risk_level', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('rest_required', sa.Boolean(), nullable=False),
    sa.Column('recommended_rest_count', sa.Integer(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('current_continuous_exposure_minutes >= 0', name=op.f('ck_risk_assessments_current_exposure_nonnegative')),
    sa.CheckConstraint('expected_continuous_exposure_minutes >= 0', name=op.f('ck_risk_assessments_expected_exposure_nonnegative')),
    sa.CheckConstraint('humidity BETWEEN 0 AND 100', name=op.f('ck_risk_assessments_humidity_range')),
    sa.CheckConstraint('recommended_rest_count BETWEEN 0 AND 1', name=op.f('ck_risk_assessments_recommended_rest_count_range')),
    sa.CheckConstraint('rest_required IN (0, 1)', name=op.f('ck_risk_assessments_rest_required_boolean')),
    sa.CheckConstraint('risk_score BETWEEN 0 AND 100', name=op.f('ck_risk_assessments_risk_score_range')),
    sa.CheckConstraint('walking_minutes >= 0', name=op.f('ck_risk_assessments_walking_minutes_nonnegative')),
    sa.ForeignKeyConstraint(['route_option_id'], ['route_options.id'], name=op.f('fk_risk_assessments_route_option_id_route_options')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments'))
    )
    op.create_index(op.f('ix_risk_assessments_route_option_id'), 'risk_assessments', ['route_option_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_assessments')
    op.drop_table('activity_logs')
    op.drop_table('route_options')
    op.drop_table('route_segments')
    op.drop_table('schedules')
    op.drop_table('work_sessions')
    op.drop_table('visit_targets')
    op.drop_table('cooling_spots')
    # ### end Alembic commands ###
